networks:
  dev:
    driver: bridge

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    
  app:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    container_name: app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev

volumes:
  postgres_data: